### ISSUE TITLE
Port map error?

### ISSUE THREAD

**Issue by parish99** [maxtacu/echo-speaks-docker#1]
Is this a typo on Dockerhub?

docker run -d -p 8081:8081 --name echo-speaks-server maxtacu/echo-speaks-server:latest

Is the internal docker port supposed to be 

docker run -d -p 8081:8091 --name echo-speaks-server maxtacu/echo-speaks-server:latest

Thanks,

**Comment by maxtacu** [comment]
Yep. Thanks for noticing! Updated docs in Dockerhub
